name: savoietek2
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9460573440883309
  lightness: 0.1944257237482816
  saturation: 0.7584932867903262
  rhythmicContrast: 0.8302764254622161
purpose: []
